services:
  db:
    image: mysql:8.0
    container_name: mysql_cosplay
    environment:
      MYSQL_ROOT_PASSWORD: agill
      MYSQL_DATABASE: chocomintcos
    ports:
      - "8306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cosplay
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: agill
    ports:
      - "8000:80"
    restart: always

volumes:
  db_data:
